language: node_js

node_js:
  - 9
  - 8

script:
  - npm run build
  - npm run test:CI

notifications:
  email:
    on_failure: change

after_success:
  - npm run test:cover:CI

cache:
  yarn: true
  directories:
    - node_modules
